# Default values for license-provision-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# namespace to lookup Magnolia instances
namespace: default
authSecretName: magnolia-auth-key
privateKeyPath: "/auth/private.pem"

# license registration info
customer: ""
magnoliaVersion: ""

image:
  repository: registry.magnolia-platform.com/operations/license-provision
  pullPolicy: IfNotPresent
  tag: "v0.1.5"

imagePullSecrets:
  - name: gitlab
nameOverride: ""
fullnameOverride: ""

cronjob:
  # job timeout: 5 minutes
  startingDeadlineSeconds: 300
  # keep a finished job for a day
  ttlSecondsAfterFinished: 86400
  # At 02:00 on every day-of-month
  schedule: "0 2 */1 * *"
  suspend: false

license:
  server: "https://license.int.magnolia-platform.com"
  username: ""
  password: ""
  # check license expiration before renewing
  # required: info.magnolia.cloud:magnolia-cloud-bootstrapper version >= 1.0.1-SNAPSHOT
  # require: info.magnolia.cloud:magnolia-cloud-bootstrapper-enterprise version >= 1.0.1-SNAPSHOT
  checkLicense: false

httpDebug: false
magnolia:
  # syntax kubectl selector
  labelSelector: "chart=magnolia-helm,tier=app"
  # tomcat port (default 8080)
  port: "8080"  

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

