apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-oauth2-proxy-helm.fullname" . }}
  labels:
    {{- include "simple-oauth2-proxy-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4180
      protocol: TCP
      name: oauth2
  selector:
    {{- include "simple-oauth2-proxy-helm.selectorLabels" . | nindent 4 }}
