{{- $fullName := include "simple-keycloak-helm.fullname" . -}}
{{- $labels := include "simple-keycloak-helm.labels" . -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    {{- $labels | nindent 4 }}
  annotations:
    # keep this secret when the release is deleted
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  # first install, generate random password
  {{- if .Release.IsInstall }}
  password: {{ randAlphaNum 20 | b64enc }}
  # subsequence upgrade, reuse existing secret
  {{ else }}
  password:  {{ index (lookup "v1" "Secret" .Release.Namespace $fullName).data "password" }}
  {{ end }}
  username: {{ "admin" | b64enc | quote }}