{{- $fullName := include "simple-keycloak-helm.fullname" . -}}
{{- $labels := include "simple-keycloak-helm.labels" . -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    {{- $labels | nindent 4 }}
  annotations:
    # keep this secret when the release is deleted
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  # retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
  {{- $secret := (lookup "v1" "Secret" .Release.Namespace $fullName).data | default dict }}
  # set $password to existing secret data or generate a random one when not exists
  {{- $password := (get $secret "password") | default (randAlphaNum 20 | b64enc) }}
  password: {{ $password | quote }}
  username: {{ "admin" | b64enc | quote }}