{{- $fullName := include "license-provision-helm.fullname" . -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-cred" $fullName }}
  labels:
    {{- include "license-provision-helm.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.license.username | b64enc | quote }}
  password: {{ .Values.license.password | b64enc | quote }}