{{- $fullName := include "license-provision-helm.fullname" . -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "license-provision-helm.serviceAccountName" . }}
  labels:
    {{- include "license-provision-helm.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ printf "%s-role" $fullName }}
  labels:
    {{- include "license-provision-helm.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ printf "%s-rolebinding" $fullName }}
  labels:
    {{- include "license-provision-helm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ printf "%s-role" $fullName }}
subjects:
- kind: ServiceAccount
  name: {{ include "license-provision-helm.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}